--- #YAML:1.0
name:                Net-Abuse-Utils
version:             0.07
abstract:            Routines useful for processing network abuse
license:             perl
author:              
    - Michael Greb <mikegrb@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Email::Address:                0
    Net::DNS:                      0
    Net::Whois::IP:                0
    perl:                          5.006_001
build_requires:
    Test::More                     0
provides:
    Net::Abuse::Utils
    file: lib/Net/Abuse/Utils.pm
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
