# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Abuse-Utils
version:      0.06
version_from: lib/Net/Abuse/Utils.pm
installdirs:  site
requires:
    Email::Address:                0
    Net::DNS:                      0
    Net::Whois::IP:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
